### ISSUE TITLE
Be consistent with use of "randomness," "random bytes," and "entropy"

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-cremers-cfrg-randomness-improvements#13]
OpenSSL uses "entropy" as a bitstream to feed into its CSPRNG, and what you get out is "random bytes."  We use the word "randomness" rather than say thing like "a measure of the entropy in the bytes."

**Comment by smyshsv** [comment]
I'd propose using "initial entropy" for the data fed into CSPRNG.
Outputs may be called "pseudorandom bytes", but despite it matches the mathematical definitions, it has a somewhat negative flavour, so I agree with "random bytes".

**Comment by smyshsv** [comment]
The issue was addressed in -03 version.

Closing.
