### ISSUE TITLE
Clarify what parts of the protocol are implemented within a HSM, and which are implemented outside

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-cremers-cfrg-randomness-improvements#14]

**Comment by smyshsv** [comment]
Added.

"  If a private key sk is stored and used inside an HSM, then the
   signature calculation is implemented inside it, while all other
   operations (including calculation of a hash function, Extract and
   Expand functions) can be implemented either inside or outside the
   HSM."

Closing.
