### ISSUE TITLE
Consider running separate DRBG and XORing with G(x)

### ISSUE THREAD

**Issue by chris-wood** [chris-wood/draft-cremers-cfrg-randomness-improvements#19]
Maybe we can list this as an alternative design for now.

**Comment by smyshsv** [comment]
An alternative design was proposed and discussed. Though at the end of the day (after all of the authors understood the idea in the same way) everyone agreed that the change doesn't seem to hurt security, it also doesn't help with performance either. 

So: considered, but left behind.

I'd propose to close the issue.

**Comment by chris-wood** [comment]
Agreed. We can close it.
